# Generated by Django 3.1.7 on 2021-04-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['-update_date']},
        ),
    ]
