# Generated by Django 3.1.7 on 2021-04-28 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_set',
            new_name='included_set',
        ),
    ]
