# Generated by Django 3.1.7 on 2021-03-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(default='South Korea', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='plan',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Basic'), (2, 'PREMIUM')], default=1),
        ),
    ]
