# Generated by Django 3.1.7 on 2021-03-27 06:29

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Basic'), (2, 'PREMIUM')], default=1),
        ),
    ]
