# Generated by Django 3.1.7 on 2021-03-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210327_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='plan',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Basic'), (2, 'Premium')], default=1),
        ),
    ]
