# Generated by Django 3.1.7 on 2021-07-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210327_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='male.png', upload_to='profile_pics'),
        ),
    ]
